/**
 * Http52112071189190TalentWebRestLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('Http52112071189190TalentWebRestLib')
    .factory('Configuration', [Configuration]);

    function Configuration() {
        return {
            //The base Uri for API calls
            BASEURI : 'http://52.11.207.118:9190/talent-web/rest'

        };
    }

}(angular));
