/**
 * Http52112071189190TalentWebRestLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
	'use strict';

	angular.module('Http52112071189190TalentWebRestLib', ['angularMoment']);

}(angular));